command: ["npm", "run", "start"]
runtime: nodejs22

env:
  - name: DATABRICKS_SERVING_ENDPOINT
    valueFrom: serving-endpoint

  - name: DATABRICKS_SERVING_ENDPOINT_KA
    valueFrom: serving-endpoint-ka

  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: experiment
