command: ["npm", "run", "start"]
runtime: nodejs22

env:
  - name: DATABRICKS_SERVING_ENDPOINT
    valueFrom: serving-endpoint

  - name: DATABRICKS_SERVING_ENDPOINT_KA
    valueFrom: serving-endpoint-ka

  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom: genie-space

  - name: LOG_SSE_EVENTS
    value: "true"